#spring.datasource:
#  url: jdbc:mysql://localhost/InvoiceDatabase?createDatabaseIfNotExist=true
#  username: root
#  password:
#  driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoicedb
    username: postgres
    password: pgroot
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: true # Optional property
    hibernate:
      ddl-auto: update # Optional property
      show-sql: true # Optional property
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

springdoc:
  api-docs.path: /api-docs

  #spring:
  #  jpa:
  #    open-in-view: true
  #    hibernate:
  #      ddl-auto: update
  #    show-sql: true

  jackson:
    mapper:
      accept-case-insensitive-enums: true
