spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: true # Optional property
    hibernate:
      ddl-auto: update # Optional property
      show-sql: true # Optional property
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

springdoc:
  api-docs.path: /api-docs

  jackson:
    mapper:
      accept-case-insensitive-enums: true
